version: '2'

services:
    app:
        build: ./webrecorder
        command: uwsgi /code/apps/frontend.ini

        env_file:
            - ./wr.env

        depends_on:
            - webagg
            - recorder
            - redis
            - shepherd

        volumes:
            - ./webrecorder/:/code/
            - ./webrecorder/proxy-certs:/code/proxy-certs

        networks:
            - default
            - browsers

    frontend:
        build:
            context: ./frontend

        environment:
            NODE_ENV: production

        depends_on:
            - app

        volumes:
            - ./frontend/:/opt/app
            - /opt/app/node_modules

        ports:
            - 3000:3000
            - 3001:3001


    recorder:
        build: ./webrecorder
        command: uwsgi /code/apps/rec.ini

        env_file:
            - ./wr.env

        depends_on:
            - webagg
            - redis

        volumes:
            - ./webrecorder/:/code/
            - ./data:/data

    webagg:
        build: ./webrecorder
        command: uwsgi /code/apps/load.ini

        env_file:
            - ./wr.env

        depends_on:
            - redis

        volumes:
            - ./webrecorder/:/code/
            - ./data:/data

    nginx:
        build: ./nginx
        image: webrecorder/nginx
        depends_on:
            - app

        volumes:
            - ./data:/data
            - ./webrecorder/:/code/

        ports:
            - "8089:80"

    shepherd:
        image: oldwebtoday/shepherd

        command: uwsgi uwsgi.ini --mount /api/browsers=/shepherd/main.py

        env_file:
            - ./wr.env

        environment:
            - SCREEN_WIDTH=1280
            - SCREEN_HEIGHT=800

            - PROXY_HOST=app
            - PROXY_PORT=8088
            - PROXY_GET_CA=http://wsgiprox/download/pem

            - CLUSTER_NAME=wr_users
            - NETWORK_NAME=webrecorder_browsers

            - CONTAINER_EXPIRE_SECS=1200
            - IDLE_TIMEOUT=120

        depends_on:
            - redis

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    redis:
        build: ./redis

        env_file:
            - ./wr.env

        ports:
            - "6379:6379"

        volumes:
            - ./data:/data

    # Postfix (if sending mail locally)
    mailserver:
        restart: always
        image: catatnight/postfix

        environment:
            - "maildomain=localhost"
            - "smtp_user=test:archive"

networks:
    default:
        driver: bridge


    browsers:
        driver: bridge

